app:
  name: "mall"
  mode: "dev"
  start_time: "2023-04-23"
  machine_id: 1
  version: "v0.0.1"
  port: 8080
auth:
  jwt_expire: 2 #定义过期时间,以两小时为例
log:
  level: "debug"
  filename: "mall.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "miku1314"
  dbname: "go-mall"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100

qiniu:
  access_key: zMUN0pBLWwekzPpwzEnMAoB1nhfNvIRWLxLTlgln
  serect_key: O5qtXbOypouarVBzeiRJSuHjzoM_OURRrPk-tSps
  bucket: clinx
  qiniuServe: hn-bkt-clouddn-com-idvcz9d.www.qiniudns.com

email:
  valid_email: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
  smtp_host: smtp.qq.com
  smtp_email: 2777526488@qq.com
  smtp_pass: tcohyrbwmyrodfij